name: Build test and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.1]
    steps:
    - uses: actions/checkout@v2
    - name: Install and run lint
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.1]
    steps:
    - uses: actions/checkout@v2
    - name: Install and run lint
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.1]
    steps:
    - uses: actions/checkout@v2
    - name: Install and run lint
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build
